name = "custom_cisco32"
sys_prompts = []
interactions = []
more_patterns = ["^.*?--More--.*?$"]
error_patterns = [
    "^% Invalid input detected",
    "^% Incomplete command",
]
ignore_errors = []

[[prompts]]
state = "Enable"
patterns = ['^[^\s#]+#\s*$']

[[prompts]]
state = "Config"
patterns = ['^\S+\(\S+\)#\s*$']

[[transitions]]
from = "Enable"
command = "conf t"
to = "Config"
is_exit = false
format_sys = false

[[transitions]]
from = "Config"
command = "end"
to = "Enable"
is_exit = true
format_sys = false
